version: 'build-{build}-{branch}'

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          CXX: g++-7
          CC: gcc-7
          BUILD_COVERAGE: ON
          CXX_STANDARD: 14
          fast_finish: true
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          TOOLCHAIN: msvc15
          compiler: Visual Studio 15 2017
          generator: "Visual Studio 15 2017"
          CXX_STANDARD: 14
          fast_finish: true
    
build:
    verbosity: detailed
  
init:
    - git config --global core.autocrlf input
#clone_folder: c:\src # выбираем локальную директорию для клонирования
shallow_clone: true # копируем только последний коммит, без истории (git clone --depth 1)

skip_commits:
    files:
      - docs/*
      - LICENSE
      - README.md
      - .travis.yml
      - codecov.yml
      - .gitignore

platform:
    - x64    
    - x86

configuration:
    - Release

branches:
  only:
    - master
    - develop
    
########## LINUX ##########
for:
-
    matrix:
        only:
            - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          
    environment:
        BUILD_CONFIG: $(configuration)
        APPVEYOR_RDP_PASSWORD: 1234as!&
        OS: linux

    install:
        - echo "Downloading conan..."
        - sudo apt-get install libpthread-stubs0-dev
        - sudo python -m pip install conan --upgrade
        - sudo python -m pip install conan_package_tools
        - conan --version
        - conan remote clean
        - conan remote add conan-center https://conan.bintray.com
        - conan remote add bincrafters https://api.bintray.com/conan/conan-community/conan
        - conan remote list
        - conan user # It creates the conan data directory
        
        - echo %PROCESSOR_ARCHITECTURE%
        - echo %CONFIGURATION%


    before_build:
      - cmd: dir
      - mkdir build && cd build
      - conan install ..
      - cmake -DBUILD_TESTS=ON ..
        
    build_script:
      - cmake --build .

    test_script:
        - ctest .

    on_finish:
        #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    artifacts:
        - path: ./build
          name: %OS%.%PROCESSOR_ARCHITECTURE%
    deploy:
        release: algo-v0.0.$(APPVEYOR_BUILD_VERSION)
        provider: GitHub
        auth_token:
            secure: rgUyfEpChawQnVOxTng38h23UY27dyfSc3sat+8d5pCXnv3yVB2hUbSwOZ9HFlRF # your encrypted token from GitHub
        artifact: ./build
        draft: false
        prerelease: false
        on:
            branch: master                 # release from master branch only
            APPVEYOR_REPO_TAG: true        # deploy on tag push only 

########## WINDOWS ##########
-
    matrix:
        only:
            - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    environment:
        PYTHON: C:\\Python37
        BUILD_CONFIG: $(configuration)
        APPVEYOR_RDP_PASSWORD: 1234as!&
        OS: windows

    install:
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
        - set PATH=%PATH%;%PYTHON%/Scripts/
        - set PATH=%PATH%;C:/Program Files (x86)/Conan/conan
    
        - cmd: echo "Downloading conan..."
        - pip install conan --upgrade
        - pip install conan_package_tools
        - conan user # It creates the conan data directory
        - cmd: conan --version
        - conan remote add conan-center https://conan.bintray.com
        - conan remote add bincrafters https://api.bintray.com/conan/conan-community/conan
        - conan remote list
        
        - cmd: ECHO %PROCESSOR_ARCHITECTURE%
        - cmd: reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Environment" /v PROCESSOR_ARCHITECTURE
        - cmd: echo %CONFIGURATION%

    before_build:
        - cmd: dir
        - mkdir build && cd build
        - conan install ..
        - cmake -A %platform% -G "Visual Studio 15 2017" -DBUILD_TESTS=ON ..
        
    build_script:
        - cmake --build .

    test_script:
        - ctest .

    on_finish:
        #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

    artifacts:
        - path: ./build
          name: %OS%.%PROCESSOR_ARCHITECTURE%

    deploy:
        release: algo-v0.0.$(APPVEYOR_BUILD_VERSION)
        provider: GitHub
        auth_token:
            secure: rgUyfEpChawQnVOxTng38h23UY27dyfSc3sat+8d5pCXnv3yVB2hUbSwOZ9HFlRF # your encrypted token from GitHub
        artifact: ./build
        description: "release algo-v0.0.$(APPVEYOR_BUILD_VERSION)" 
        draft: false
        prerelease: false
        on:
            branch: master                 # release from master branch only
            APPVEYOR_REPO_TAG: true        # deploy on tag push only 